name: fast_element
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: jjfp <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.1'

dependencies:
  core:
    path: C:/acr/odw/sdk/core
    version: ^0.7.0

dev_dependencies:
  test: ^0.12.0
